### ISSUE TITLE
Perf: extend Vertex status with BIT_TIN_MEMBER

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#11]
I suggest to extend Vertex status with new flag "TIN MEMBER". It will be set after inserting Vertex to TIN. And will be used in 'addWithInsertOrAppend' to skip calling 'walker.findAnEdgeFromEnclosingTriangleInternal' becuase it is known that Vertex is already inserted.

I use Hilbert Sort to improve performance.

1) construct Vertex List from all vertices including from Constraints
2) sort vertices with Hilbert Sort
3) add vertices to TIN
4) add constraints to TIN
  - here we can skip inserting already known vertices
  - constraint vertices cannot be sorted with Hilbert Sort

```
class Vertex {
  public static final int BIT_TIN_MEMBER = 0x04;
...
  public boolean isTINMember(){
    return (status&BIT_TIN_MEMBER)!=0;
  }

  public void addStatus(int status){ 
    this.status |= (byte)status;
  }
}

private boolean addWithInsertOrAppend(final Vertex v) {
    if (v.isTINMember()) return;
    v.addStatus(Vertex.BIT_TIN_MEMBER);
   ...
}
```
replace
`m.setStatus(Vertex.BIT_SYNTHETIC | Vertex.BIT_CONSTRAINT);
`
with
`m.addStatus(Vertex.BIT_SYNTHETIC | Vertex.BIT_CONSTRAINT);
`

**Comment by gwlucastrig** [comment]
I'm still going through the many suggestions you made today.  This is the only one about which I have some reservations.  I'd like to get a bit more information about what you are trying to accomplish with this.

One of the basic rules for Tinfour is that it doesn't modify a sample vertex when you add it to the TIN.  The vertices belong to the application code, not the TIN.  Also, it is possible that a vertex could be added to multiple TINS all at the same or in sequence.  The Tinfour Viewer application reuses the same vertices over and over again.   Also, once a TIN gets disposed, or goes out-of-scope, the vertex would no longer be a member of that TIN.

So as implemented, BIT_TIN_MEMBER would tell an application that a vertex had been a member of  a TIN at some point, but wouldn't tell whether it was currently a member. 

The "setStatus" method you mention is only used for vertices that are created synthetically by Tinfour when trying to restore Delaunay conformality.  The addStatus method that you propose would work just as well.  So I have no problem with that change.

It occurs to me that the IConstraint classes are setting the constraint status bits on the vertices they accept.  I think that is purely diagnostic at this time...  I'll have to review it to see if it is appropriate.

**Comment by jandam** [comment]
You have deep knowledge of your library and rules of usage. Today I was focused to improve performance on my test with minimal changes. So why I'm reporting this for your decision. Your are right. My vertex cannot be reused.
I want you know what I'm doing. I need some more time to dig deeper in your great code. 

Martin JANDA

26. 1. 2017 v 20:21, gwlucastrig <notifications@github.com>:

**Comment by gwlucastrig** [comment]
In my latest few updates to the class, I've formally set aside three member elements reserved0, reserved1, and reserved2 that are available for your use.  You can always extend Vertex by writing your own class and using them anyway you see fit.   Doing so will not increase the memory use of Vertex objects.

When I say "set aside" it basically means that I am promising the world that I will never make any changes that will prevent anyone from using those fields....   I do not foresee ever needing to use those elements in Tinfour.  Hmmm....  Now, I'm getting a little nervous about that.  Maybe you better just use reserved0 and reserved1 and leave reserved2 alone just in case.

**Comment by gwlucastrig** [comment]
No change made to code at this time....  I may investigate this further in future pending your results.  Feel free to re-open this issue or otherwise let me know if you have any more ideas on this issue.

**Comment by jandam** [comment]
Thank you very much for fixing all reported bugs.
This improvement should be fixed after  #9 custom Vertex storage.
  As you said Vertex is stateless and can be reused multiple times. My idea is to have "stateful" vertex.
No-op method 'getAndSetTINMember' is added to Vertex to eliminate instanceof checks in code.

```
public class Vertex {
...
    public boolean getAndSetTINMember(final boolean tinMember) {
        return false;
    }
}

public class VertexWithState extends Vertex {
  priavte boolean tinMember = false;  // new boolean field or reuse field from Vertex

    @Overrride
    public boolean getAndSetTINMember(final boolean tinMember) {
        boolean oldValue = this.tinMember;
        this.tinMember = tinMember;
        return oldValue;
    }
}
```

**Comment by gwlucastrig** [comment]
Your approach is a classic use of class inheritance.  My only suggestion would be to use one of the so-called "reserved" elements in the Vertex class rather than adding an additional element.  By using one of the existing elements, you will prevent the in-memory size of your VertexWithState objects from growing any larger than the existing class.

Actually, here's something to investigate.  The memory size of Java objects (at least using the HotSpot JVM) have to be a multiple of eight.  When I was experimenting with a variety of designs for the Vertex class, I knew that the member elements plus Java overhead added up to 37 bytes, so I had three bytes to spare.   So when I added those reserved elements, the in-memory size of Vertex instances did not increase.  You can see a discussion of this idea in the comments in the Vertex source code.

Now here's where I may have made a mistake...  It appeared that if I left the reserved elements out of the Vertex class, but added , and added a single one-byte field to a derived class, the in-memory size of the instances increased by 8 bytes.  It was almost as if Java could not take advantage of the available three bytes padding in the parent class, but had to keep memory used by the derived class separate from that used by the parent class.  This observation is what led me to add the "reserved" elements to the Vertex class in the first place.

In ordinary applications, we wouldn't care about memory details.  But given that you are creating something like 80 million Vertex objects, it could be significant.  So perhaps you will find that your memory use is smaller if you use one of the reserved elements rather than adding a new one. 

If you do try this, please let me know what you find out.   If you would like to see some example code of how I evaluated memory, you may refer to the SingleBuildTest class.  It has some logic for tracking memory use.  But, also, do not take everything I say as absolutely authoritative.  I do not claim that my approach is perfect.  It seems to me that Java hides some of the details of memory management.  And I am not an expert on this subject.

**Comment by jandam** [comment]
Hi,
   you mention that object size is increased in 8 byte steps. I think thats due to compressed oops optimization in  virtual machine for heap sizes < ~25GB.
In 32bit JVM pointer size is 4 bytes. Heap size <2GB. For 64bit JVM pointer size is 8bytes - 64 bits. Compressed opps use 32bit pointer multiplied by 8 for heaps smaller than ~ 25GB. To save memory. I don't remember correct maximum. For larger heaps pointer is switched to full 64bits. Please search for 'Compressed oops'

Martin JANDA

6. 2. 2017 v 13:52, gwlucastrig <notifications@github.com>:

**Comment by gwlucastrig** [comment]
Thanks.   There are so many clever optimizations in various JVM's that it is difficult to keep up with them. The one that really surprised me was escape analysis.  One day my code just started running faster and I didn't know why.  I was grateful, of course. But it did mean that a lot of the effort I put into avoiding creating short-persistence objects was unnecessary.  I'm looking forward to the day when the Java team implements value types.

Incidentally, I have another thought.  So far, I have been trying to maintain object-code compatibility with older JVM's, so I always compile my code using a Java 7 compiler.   I wonder if there might be a performance gain if the code were compiled using a Java 8 version of the Java compiler.   Have you been running your tests using the Jars you downloaded from the Tinfour project?  Have you tried compiling your own?

**Comment by jandam** [comment]
I think that there is no performance gain when compiled by Java 8. Latest changes (maybe already in Java 7) are 'class' file pre-validation during compilation to improve class loading times. There should be another change in code generation for String concat to help future optimization in Hotspot. 
I have self compiled version by Java 8 with fixes for issues that I reported. I don't see any speed improvements. 
So far I didn't try your latest release.

**Comment by gwlucastrig** [comment]
The latest release was focused on adding the Constrained Delaunay Triangulation functions to the Tinfour Viewer and shouldn't affect performance either way.
