### ISSUE TITLE
Infinite/almost infinite adding vertices to constraint

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#16]
New vertices are added to PolygonConstraint in SemiVirtualIncrementalTin::processConstraint. As can be seen there are only 2 repeating Vertex instances in this range.

19900 = {Vertex@8798} " 0: x=-673.6734854805982, y=922.2082379390486, z=211.81076"
19901 = {Vertex@8793} " 0: x=-673.673485453357, y=922.2080292212777, z=211.81073"
19902 = {Vertex@8798} " 0: x=-673.6734854805982, y=922.2082379390486, z=211.81076"
19903 = {Vertex@8793} " 0: x=-673.673485453357, y=922.2080292212777, z=211.81073"
19904 = {Vertex@8798} " 0: x=-673.6734854805982, y=922.2082379390486, z=211.81076"
19905 = {Vertex@8793} " 0: x=-673.673485453357, y=922.2080292212777, z=211.81073"
19906 = {Vertex@8798} " 0: x=-673.6734854805982, y=922.2082379390486, z=211.81076"

**Comment by jandam** [comment]
Attached code to reproduce the issue
`
    private static final String[][] DATA_2 = {
            {
                    "0;-667.4102878975682;925.6030547851697",
                    "32;-673.5715825763764;921.9746538009495",
                    "33;-673.6734854805982;922.2082379390486",
                    "34;-673.727860343759;922.4572140970267",
                    "48;-667.4102878975682;925.6030547851697"
            },
            {
                    "0;-668.0264828265645;927.5057643828914",
                    "1;-667.4775539539934;927.6256470771203",
                    "43;-675.0262939281529;924.6542789670639",
                    "54;-668.0264828265645;927.5057643828914"
            },
            {
                    "0;-711.3335265977075;1047.543736491818",
                    "60;-672.7742737252668;919.3327389855313",
                    "61;-673.673485453357;922.2080292212777",
                    "62;-674.6306821039561;925.0649443285723",
                    "63;-680.4068052946986;942.3047597780921",
                    "102;-711.3335265977075;1047.543736491818",
            }
    };

    public static void main(final String[] args) {
        List<IConstraint> constraintList = new ArrayList<>(DATA_2.length);
        for (String[] data : DATA_2) {
            PolygonConstraint constraint = new PolygonConstraint();
            Coordinate[] coords = new Coordinate[data.length];
            for (int index = 0; index < data.length; index++) {
                String text = data[index];
                String[] values = text.split(";");
                double x = Double.parseDouble(values[1]);
                double y = Double.parseDouble(values[2]);
                Vertex vertex = new Vertex(x, y, 1.0);
                constraint.add(vertex);

                coords[index] = new Coordinate(x, y, 1.0);
            }
            constraint.complete();
            constraintList.add(constraint);
        }

        double nominalPointSpacing = 10.0;
        IIncrementalTin tin = new SemiVirtualIncrementalTin(nominalPointSpacing);
        tin.addConstraints(constraintList, false);
    }
`

**Comment by jandam** [comment]
Modification to PolyLineConstraintAdapter to detect this issue.

`
public abstract class PolyLineConstraintAdapter implements IConstraint, Iterable<Vertex> {

  protected final List<Vertex> list = new ArrayList<Vertex>() {
    @Override
    public void add(final int index, final Vertex element) {
      if (index > 2 && get(index - 2) == element) {
        throw new IllegalStateException("Creating circle");
      }
      super.add(index, element);
    }
  };
...
`

**Comment by gwlucastrig** [comment]
Thanks
 I will look at this and try to get a fix to you soon.

**Comment by jandam** [comment]
Here: Self-intersection at or near point (-674.5571255117115, 924.8454022527688, NaN) at row with ID=62

**Comment by gwlucastrig** [comment]
I did this in a hurry, so you should probably check my math. I seem to be finding a number of intersections in the geometry of the constraints.  One of Tinfour's requirements for constraints is that they do not intersect each other, except perhaps at endpoints.  So it may be that the only way to address this issue is to write a utility that tests a set of constraints for intersections and produces a new set constraints that prevent this issue.

In the text below, I printed out the input parameters from your strings and the places I found intersections.  Again, you should double check these, since I could have made a mistake.  The "intersect" indicates which line and segment intersected, so 0:00, 2:00 means line 0 intersected line 2 both at the first segment.   The parameter are the parametric coordinates for the intersections.  So a value of (0.25, 0.5) would mean that the intersection was 1/4 the way into the first segment and 1/2 way into the second.

 
<pre>
INPUT
      x               y            length
  0  -667.410288   925.603055 |   7.15
  1  -673.571583   921.974654 |   0.25
  2  -673.673485   922.208238 |   0.25
  3  -673.727860   922.457214 |   7.06
  4  -667.410288   925.603055

  0  -668.026483   927.505764 |   0.56
  1  -667.477554   927.625647 |   8.11
  2  -675.026294   924.654279 |   7.56
  3  -668.026483   927.505764

  0  -711.333527  1047.543736 |  133.88
  1  -672.774274   919.332739 |   3.01
  2  -673.673485   922.208029 |   3.01
  3  -674.630682   925.064944 |  18.18
  4  -680.406805   942.304760 |  109.69
  5  -711.333527  1047.543736
  
OUTPUT   
intersect   0:00   2:00
     ( -667.410288   925.603055),  ( -673.571583    921.974654)
     ( -711.333527  1047.543736),  ( -672.774274    919.332739)
  at ( -673.569240   921.976033)  parameters(0.9996, 0.9794)
intersect   0:03   2:00
     ( -673.727860   922.457214),  ( -667.410288    925.603055)
     ( -711.333527  1047.543736),  ( -672.774274    919.332739)
  at ( -673.715766   922.463237)  parameters(0.0019, 0.9756)
intersect   1:01   2:00
     ( -667.477554   927.625647),  ( -675.026294    924.654279)
     ( -711.333527  1047.543736),  ( -672.774274    919.332739)
  at ( -674.443688   924.883607)  parameters(0.9228, 0.9567)
intersect   1:01   2:02
     ( -667.477554   927.625647),  ( -675.026294    924.654279)
     ( -673.673485   922.208029),  ( -674.630682    925.064944)
  at ( -674.555217   924.839706)  parameters(0.9376, 0.9212)
intersect   1:02   2:00
     ( -675.026294   924.654279),  ( -668.026483    927.505764)
     ( -711.333527  1047.543736),  ( -672.774274    919.332739)
  at ( -674.445833   924.890739)  parameters(0.0829, 0.9566)
intersect   1:02   2:02
     ( -675.026294   924.654279),  ( -668.026483    927.505764)
     ( -673.673485   922.208029),  ( -674.630682    925.064944)
  at ( -674.557126   924.845402)  parameters(0.0670, 0.9232)
 </pre>

**Comment by jandam** [comment]
Yes this is why I reported "Self-intersection at or near point" that is validation error from Java Topology Suite. I have to check input data and add new vertices at intersections.

**Comment by gwlucastrig** [comment]
Excellent!  

Do you believe that this particular issue (#16) is now sufficiently addressed that I can close it?

I'm glad you know about the JTS.  I was going to recommend it.

From time to time, I have considered writing a utility that could be used to "groom" a set of constraints and ensure that the Tinfour input conditions are met.  But I think that JTS has done it so much better than I would.

**Comment by gwlucastrig** [comment]
I believe that no further action is required for item 16. Therefore, I am closing it. Please open a new issue if there are further developments.  

As always, thanks for the feedback.
