### ISSUE TITLE
RFE: replace xxxPinwheel with one class

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#22]
QuadEdgePinwheel and SemiVirtualPinwheel can be replaced with one common implementation. Only difference is that QuadEdgePinwheel unnecessary uses more strict QuadEdge fields instead of IQuadEdge interface.

**Comment by gwlucastrig** [comment]
You are correct.

The original plan for the implementation was to use custom code in the semi-virtual pinwheel operation to reuse semi-virtual edge instances.   The idea was to avoid short term instances of edge objects and the associated overhead due to garbage collection.  But with improvements in Java's optimization through escape analysis this particular class didn't need special coding for semi-virtual edges.  

I will modify the code following your suggestion in the next week or so.

**Comment by gwlucastrig** [comment]
The pinwheel-related classes have now been consolidated.  Thank you for your suggestion.

This issue is now closed.
