### ISSUE TITLE
SemiVirtualTIN: NPE - invalid reuse/load edge during construction

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#23]
SemiVirtualTIN throws NPE during tin construction due to invalid modifying/loading search edge. SearchEdge is always valid (vertices A != null and B != null). But in 7 cases / 21 000 of TINs creations throws NPE because search edge is loaded with "outline" edge. I'm working on locating the problem.
So far I've replaced all edge reuses with creating new instance. There is no exception anymore after modification. Standard TIN is correct.

**Comment by gwlucastrig** [comment]
I'll look through the code tonight and see if I can find any likely causes for this issue.  

I am not quite sure what you mean when you say "creating new instance".   Are you calling edgePool.getStartingEdge().   That should always work, but it will slow down the speed at which new points are added to the TIN...  In general, it will increase the average number of steps in a Stochastic Lawson's Walk to find the insertion triangle.  Of course, that all depends on the geometry of your input points.

**Comment by jandam** [comment]
I'm sorry for incomplete info. I replaced all usages of findAnEdgeFromEnclosingTriangleInternal with findAnEdgeFromEnclosingTriangle from SemiVirtualStochasticLawsonsWalk.

And replaced all calls in SemiVirtualIncrementalTin to 
searchEdge = walker.findAnEdgeFromEnclosingTriangle(searchEdge, x, y);
...
I modified code to be almost same as in IncrementalTin removing all reusing of SemiVirtualEdge.

**Comment by gwlucastrig** [comment]
I hope to get the Tinfour code into a state where you can use it directly from the project without having to make modifications.   I'm having a little trouble following your explanations of the changes.  Would it be possible to send me a copy of your SemiVirtualIncrementalTin.java ?    Also, would it be possible to send me one of the test data sets that triggers the NPE?

Thanks.

**Comment by jandam** [comment]
I'm sorry. My english is horrible. Attached code is modified version. No perfectly in sync with your code. There are some differences in indentation, imports, ... due to automatic changes made by IDE.
  I have to find and isolate minimal constraints to reproduce this issue. As mentioned above important changes are in LawsonsWalk and TIN. 
SemiVirtualIncrementalTin::setSearchEdge is only for debug purposes to ensure that searchEdge is always well defined. This check always valid. But somewhere search edge is reloaded and sometimes is load with ghost edge (getB() == null) leading to NPE. This issue can't be detected when searchEdge is reloaded with correct inner edge.
   Tomorrow I will send test data.

[tin-no-npe.zip](https://github.com/gwlucastrig/Tinfour/files/1434876/tin-no-npe.zip)

**Comment by jandam** [comment]
PS there is micro optimization in DD. DD::setSubstract(<double>, <double>). I use it in GeometricOperations. It assumes that DD::lo is zero.

**Comment by jandam** [comment]
Attached code triggers NPE. Constrain is VALID (JTS validation as linestring). Data has no real meaning. It is minimal extract from 10k linear constrain. Tested on latest version: commit 102. Issue not denpends on restoreConformity parameter.

  ```
      List<IConstraint> list = new ArrayList<>();
        IConstraint constraint = new LinearConstraint();
        constraint.add(new Vertex(16.639320494143917,16.322343896187164,0.0));
        constraint.add(new Vertex(16.64387668872287,16.308092487027892,0.0));
        constraint.add(new Vertex(17.408915005253434,16.290820368381986,0.0));
        constraint.add(new Vertex(17.40891500525361,16.290820368381986,0.0));
        constraint.add(new Vertex(17.345089565983685,16.325981631318598,0.0));
        constraint.complete();
        list.add(constraint);

        IIncrementalTin tin = new SemiVirtualIncrementalTin(0.01);
        tin.addConstraints(list, false);

```

```
Exception in thread "main" java.lang.NullPointerException
	at tinfour.semivirtual.SemiVirtualStochasticLawsonsWalk.findAnEdgeFromEnclosingTriangleInternal(SemiVirtualStochasticLawsonsWalk.java:195)
	at tinfour.semivirtual.SemiVirtualIncrementalTin.addWithInsertOrAppend(SemiVirtualIncrementalTin.java:698)
	at tinfour.semivirtual.SemiVirtualIncrementalTin.add(SemiVirtualIncrementalTin.java:408)
	at tinfour.semivirtual.SemiVirtualIncrementalTin.addConstraints(SemiVirtualIncrementalTin.java:1689)

```

**Comment by jandam** [comment]
Issue is triggered at SemiVirtualIncrementalTin::checkTriangleVerticesForMatchInternal at line 891. Method has searchEdge as argument and loads invalid edge (getB == null).
SemiVirtualEdge::index, SemiVirtualIncrementalTin::searchEdge is encapsulated with getter and setter. And SemiVirtualEdge has new lock field. Setters has following code (also attached):

```
// SemiVirtualIncrementalTin
   public void setSearchEdge(SemiVirtualEdge searchEdge) {
    if (this.searchEdge != null) this.searchEdge.lock = false;
    this.searchEdge = searchEdge;
    if (this.searchEdge != null) this.searchEdge.lock = true;
  }

// SemiVirtualEdge
  boolean lock = false;
  public void setIndex(int index) {
    if (lock) {
      System.err.printf("setIndex: %d -> %d%n", this.index, index);
    }
    this.index = index;
  }

```
Output:
```
setIndex: 0 -> 5
setIndex: 5 -> 10
Exception in thread "main" java.lang.NullPointerException
	at tinfour.semivirtual.SemiVirtualStochasticLawsonsWalk.findAnEdgeFromEnclosingTriangleInternal(SemiVirtualStochasticLawsonsWalk.java:195)
	at tinfour.semivirtual.SemiVirtualIncrementalTin.addWithInsertOrAppend(SemiVirtualIncrementalTin.java:694)
	at tinfour.semivirtual.SemiVirtualIncrementalTin.add(SemiVirtualIncrementalTin.java:404)
	at tinfour.semivirtual.SemiVirtualIncrementalTin.addConstraints(SemiVirtualIncrementalTin.java:1685)
	at tinfour.test.examples.LogoCDT.main(LogoCDT.java:93)

```
[tin-commit-102-modified.zip](https://github.com/gwlucastrig/Tinfour/files/1437256/tin-commit-102-modified.zip)

**Comment by gwlucastrig** [comment]
Thank you for your excellent test case.  It led me straight to the problem.  I believe that there is an easy fix.  I have some testing to do before I post the changes, but should have a fix in the next day or so.

When the checkTriangleVerticesForMatchInternal() is called, and the input vertex is coincident (or nearly so) with one of the endpoints of the edge, the method returns a value of true.  It is also supposed to find the edge that starts with the input vertex.  So if the input vertex matches vertex B of edge A->B, the routine is suppose to return edge B->A (the dual of edge A->B).  The existing code incorrectly calls loadForwardFromEdge() rather than loadDualFromEdge().  Usually, this action is benign.  But if edge A->B is a perimeter edge, the forward is a ghost edge (B->null).  Internally, the result was stored a the search edge...  But logic in Tinfour depends on the search edge always having a valid geometry (not having any ghost vertices).  So when a subsequent insertion operation accessed the search edge, tje result was an NPE.

In your test data, vertices 3 and 4 are close enough together that the TIN treats them as coincident, though the constraint class treats them as distinct. That was a fortunate turn of events since it revealed a bug in the code.

One of my test procedures is to create a random set of vertices, feed them to the TIN class, and then run IntegrityCheck.inspect() to make sure the TIN was created correctly.  Over the last year, I have tested several million vertex insertion operations. But that test has a limitation. The problem with randomly generating vertices is that it pretty much guarantees that there will be no coincident vertices (they're not impossible, just unlikely).   I can see that I will have to modify the insertion test to salt the data with coincident vertices.

Gary


P.S. I also have tests programs for special geometries.  For example, one takes a set of vertices arranged in a regular grid, one takes a set of vertices arranged in a circle, and one starts with a random cloud of vertices but inserts a set of co-linear vertices. These are all geometries that are known to cause ambiguities with the inCircle() calculation or otherwise present challenges to the insertion algorithms I use.

**Comment by gwlucastrig** [comment]
I have posted revisions to the code that address this problem.  I am closing this issue.

Thanks to Martin Janda for his help in identifying and fixing this problem.
