### ISSUE TITLE
Missing triangles for triangle constraints

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#30]
TriangleCollector should visit all triangles. They are missing when constraint creates simple triangle.

Test data are attached in #24 . Complex roof polygon with constraints.

**Comment by gwlucastrig** [comment]
Thanks for finding this bug.  Unfortunately, I have only a partial solution at this time.  

For now, you may obtain a full set of triangles by looping on constraints and individually calling the visitTrianglesForConstrainedRegion method.   I plan on integrating this functionality into the more convenient visitTrianglesConstrained method, but have some more work to do first.  

There was a bug in the visitTrainglesForConstrainedRegion method, bit I fixed it thanks to your example.

To see what goes wrong with visitTrianglesConstrained, refer to the picture of the hipped roof example. The outer polygon is a constrained region.,The edges that define the roof line (20, 22, 26, 28) are themselves constraints.  The visitTrianglesConstrained method develops triangles by looking for edges that are marked as interior to a constrained region.  Edges 4 and 18, which were produced by the TIN-building algorithm are interior.  But the others are not. The problem comes from the limits of how much memory I am willing to allocate to edges. Tinfour has only enough room to allocate to constraint properties.  An edge can carry only a single constraint index.  Any constraint interior edge must carry the index for the constrained region to which it belongs. But a linear constraint edge must carry the index to the constraint that produced it.  Since an edge can't give two separate constraint indices, these requirements are in conflict. Therefore, Tinfour does not allow a constraint edge to be marked as a constraint region interior.  
![hippedroof](https://user-images.githubusercontent.com/19698145/32698473-76299cda-c774-11e7-9801-e2fd7b06035e.png)

The constraint region borders have a similar problem because a border edge could be a member of two adjacent regions.  Since it cannot carry an index for both regions, the constraint region index for a border edge is treated as ambiguous.

Here's some code for an alternate version of your Hipped Roof example,  Note that I have added indices to the vertices.  I often find that numbering vertices is useful for debugging.
` 
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import tinfour.common.IConstraint;
import tinfour.common.IIncrementalTin;
import tinfour.common.IIntegrityCheck;
import tinfour.common.IPolyline;
import tinfour.common.LinearConstraint;
import tinfour.common.PolygonConstraint;
import tinfour.common.Vertex;
import tinfour.utils.TriangleCollector;

public class HippedRoof {

  public static void main(String[] args) {
    double nominalPointSpacing = 0.01;
    // IIncrementalTin tin = new tinfour.standard.IncrementalTin(nominalPointSpacing);
    IIncrementalTin tin = new tinfour.semivirtual.SemiVirtualIncrementalTin(nominalPointSpacing);
    List<IConstraint> constraintList = new ArrayList<>();

    Vertex v0 = new Vertex( -5.254566785879433, -10.120986399240792,  Double.NaN, 0);
    Vertex v1 = new Vertex( 11.397855226881802,  -0.2510828208178282, Double.NaN, 1);
    Vertex v2 = new Vertex(  5.243457765551284,  10.120986400172114,  Double.NaN, 2);
    Vertex v3 = new Vertex(-11.397855226648971,   0.2683861115947366, Double.NaN, 3);

    PolygonConstraint polygon = new PolygonConstraint(v0, v1, v2, v3);
    constraintList.add(polygon);

    Vertex v4 = new Vertex( 4.862010033102706,  2.8856616728007793, Double.NaN, 4);
    Vertex v5 = new Vertex(-4.867160049267113, -2.8776928577572107, Double.NaN, 5);

    constraintList.add(new LinearConstraint(v4, v5));
    constraintList.add(new LinearConstraint(v4, v2));
    constraintList.add(new LinearConstraint(v4, v1));
    constraintList.add(new LinearConstraint(v5, v0));
    constraintList.add(new LinearConstraint(v5, v3)); 

    constraintList.forEach(IPolyline::complete);

    tin.addConstraints(constraintList, false);
    IIntegrityCheck icheck = tin.getIntegrityCheck();
    icheck.inspect();
    icheck.printSummary(System.out);

    List<IConstraint> outputList = tin.getConstraints();
    System.out.println("Obtained " + outputList.size() + " constraints");
    System.out.println("Building traingles");
    for (IConstraint constraint : outputList) {
      if (constraint.definesConstrainedRegion()) {
        TriangleCollector.visitTrianglesForConstrainedRegion(
                constraint, new Consumer<Vertex[]>() 
        {
          @Override
          public void accept(Vertex[] vArray) {
            System.out.format("    %3d %3d, %3d%n",
                    vArray[0].getIndex(),
                    vArray[1].getIndex(),
                    vArray[2].getIndex());
          }
        }
        );
      }
    }
  }
}
`

**Comment by gwlucastrig** [comment]
There remains additional work on this issue.  The current implementations of the flood-fill methods in the IIncrementalTin classes uses recursion.  This approach works beautifully and produces clean, easy-to-read code. Unfortunately, the depth of the recursive stack can be quite large.  The map-of-the-world shapefile I've been using for testing results in a max recursive depth of 786.   So I'm going to have to remove the recursion.  The resulting code will be less readable. But I think this is a necessary step.

**Comment by jandam** [comment]
Thank you. Stack (ArrayDeque - not synchronized) instead of recursion is readable too.
It looks that my problem is more complex that I'm thinking. I can better prepare data for tinfour. It can be possible for me to create extension to SemiVirtual tin. Another exercise for me.

**Comment by gwlucastrig** [comment]
Actually the test cases you're finding are very much welcome. The recursion
is something that needs to be addressed anyway.

I'm going to be quite busy with work this week.   But I hope I can find a
couple of evenings to work on this issue

**Comment by gwlucastrig** [comment]
Eliminated the recursion in the IIncrementalTin classes' flood fill methods.  Still need to work on TriangleCollector.

**Comment by gwlucastrig** [comment]
I removed the recursion from TriangleCollector.   I also modified the visitTrianglesConstrained method so that it appears to reliably collect all triangles.  I have tested it using LogoCDT, the hipped roof example, and the world-map (shapefile) test I have.  The results below are built from triangles visited using the TriangleCollector class.

![europefilled](https://user-images.githubusercontent.com/19698145/32758005-47b64032-c8b0-11e7-8042-87c4784130c2.png)

Incidentally, I've tried tests involving a very large number of points to test how large the recursive call stack would have gotten had it not been replaced with the Deque-based .   For a constrained region that contained about 278 thousand vertices, and 833999 edges, the max size of the Deque the new routine uses was 827605.  This is roughly equivalent to how deep the recursive call stack would have gotten in the old implementation, had Java not crashed first. 

I'm going to leave this Issue open for a few days.  Please let me know if you find any problems.

**Comment by jandam** [comment]
Thank you very much. I will sync and try your changes later on. Currently I have finished compact method for SemiVirtualPool. I will send you minimal modifications in tin code. And now I need to reconstruct tin after edge removal to pass integrity checks. This is critical issue for me.

**Comment by gwlucastrig** [comment]
When you compact the SemiVirtualPool, keep in mind that each constraint object that is retained in the SemiVirtualIncrementalTin instance will hold a reference to one edge object.  In the case of the polygon constraints, these edge objects will be the interior-facing edge that is used as the "firstEdge" in the TriangleCollector   visitTrianglesUsingStack() method.   So if your compact method moves edges around (and assigns them new index values), it will have to update that edge reference as appropriate.

Both the polygon and linear constraints hold a reference to one edge from the constraint.  At present, I am not using the reference from the linear constraint for any purpose, though in the future I might try to use them to construct the chain of edges that resulted from inserting a constraint into the TIN.

I am also looking at adding a method to the TriangleCollector that collects all triangles, not just those that occur in constraints.  It will actually be based on the original code that you contributed with the first version of the TriangleCollector.

**Comment by jandam** [comment]
Thank you for the hint. My code already resets SemiVirtualIncrementalTin::searchEdge. I have to check other places. I suppose that compact will be used immediately after TIN creation. So there is no interpolators, collectors holding reference to moved edge.

I didn't notice that constraint is holding reference to one of its edges.

**Comment by gwlucastrig** [comment]
If it is easier for you, it is probably sufficient to clear the searchEdge and not worry about re-populating it.  The reason for the search edge is to speed up the insertion operation when new vertices are added to the TIN. For one operation, the reduction in CPU time is almost too small to measure.  When an application add thousands (or millions) of vertices, it becomes significant.

From time to time, I have thought about giving Tinfour a "operation counter" that would keep count of all the insertions, removals, and other modifications.   Your compaction routine would change the operation count.  If an application invoked an interpolator, the interpolator could check that the count was consistent with the last time it populated its search edge.  If the count had changed, the interpolator would know that the search edge it had was obsolete and it could clear it before processing.

There is an explanation of the search edge (or "starting edge") concept under paragraph 2.2.8.2 Vertex Location in the "Data Elements and Algorithms for the Tinfour Library" document (on page 24 of the latest version).   Unfortunately, it is written in my usual dense, unreadable prose.  But I hope it should be clear enough to provide some insights on the process.

**Comment by gwlucastrig** [comment]
I have completed code changes for Issue 30.  The TriangleCollector now handles constrained regions correctly.  Additionally, the collector now includes a method for collecting all triangles in the TIN, not just those that belong to a constrained region. 

Issue 30 is now closed.
