### ISSUE TITLE
TriangularFacetInterpolator: valid average formula?

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#31]
There is code for computing average that uses twice z0. I think that it should be (z0+z1+z2)/3.0

https://github.com/gwlucastrig/Tinfour/blob/787e8ad69b7f2a47ccdfe49714f97c575d2b16f8/src/main/java/tinfour/interpolation/TriangularFacetInterpolator.java#L199

**Comment by gwlucastrig** [comment]
Good catch!

This line is reached only if the code computes a normal to the triangle's plane and the resulting vector is of length zero or nearly zero.  This condition will occur only when the three vertices lie in a straight line... In which case the triangle is degenerate (has area zero).  When Tinfour is operating properly, all the triangles should be valid and the line will never be reached.

So...  The code is wrong.  The fix is easy.  I will attend to it at my first opportunity.

I am impressed by how closely you are inspecting the Tinfour code.

**Comment by gwlucastrig** [comment]
Fix posted.  Issue is closed.  Thank you for identifying this problem.
