### ISSUE TITLE
IncrementalTIN: infinite loop in processConstraint

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#35]
https://github.com/gwlucastrig/Tinfour/blob/cfd50eb7c63061b02598375695f47c83d51f98cd/src/main/java/tinfour/standard/IncrementalTin.java#L2035

Above line is adding alternate vertices (Vertex@6135, Vertex@6131) to cvList and incrementing nSegments. More info/sample will follow

82 = {Vertex@6135} " 0: x=24.03662014933414, y=-55.7899709286193, z=-25.385998"
83 = {Vertex@6131} " 0: x=23.708504632432934, y=-55.53547969058978, z=-25.625874"
84 = {Vertex@6135} " 0: x=24.03662014933414, y=-55.7899709286193, z=-25.385998"
85 = {Vertex@6131} " 0: x=23.708504632432934, y=-55.53547969058978, z=-25.625874"
86 = {Vertex@6135} " 0: x=24.03662014933414, y=-55.7899709286193, z=-25.385998"
87 = {Vertex@6131} " 0: x=23.708504632432934, y=-55.53547969058978, z=-25.625874"

**Comment by jandam** [comment]
I think that segment is (near) collinear to e0 but segment and e0 have no common part.

Sample: 
Segment
seg0 = new Vertex(0.0, 0.0);
seg1 = new Vertex(1.0, 0.0);

E0
e00 = new Vertex(2.0, 0.0);
e01 = new Vertex(3.0, 0.0);

**Comment by gwlucastrig** [comment]
I am not absolutely sure, but I believe that this issue was fixed with various improvements to the internal computation logic that have been implemented over the last 6 months. At this time, I do not have a specific test.   So I am closing this item.  Please let me know if you encounter further problems and open a new issue if you do.

I am closing this issue.
