### ISSUE TITLE
Implement/Fix QuadEdgePartner hashCode()

### ISSUE THREAD

**Issue by micycle1** [gwlucastrig/Tinfour#62]
`hashCode()` is broken for `QuadEdgePartner` -- it always returns 77.

This is because the class doesn't define its own `hashCode()` method and uses the implementation from `QuadEdge`, but a `QuadEdgePartner` `index` is always 0.

QuadEdgePartner Constructor:
![image](https://user-images.githubusercontent.com/9304234/108913372-c2417480-7621-11eb-871e-6c27e7c4195c.png)

`QuadEdge` HashCode Method:
![image](https://user-images.githubusercontent.com/9304234/108913054-5fe87400-7621-11eb-82ad-5b7457c4e6d6.png)

They're all 77!

```
System.out.println(t.getEdgeA().hashCode() + " " + t.getEdgeA().getIndex());
System.out.println(t.getEdgeA().getClass().toString());
System.out.println(t.getEdgeB().hashCode() + " " + t.getEdgeB().getIndex());
System.out.println(t.getEdgeB().getClass().toString());
System.out.println(t.getEdgeC().hashCode() + " " + t.getEdgeC().getIndex());
System.out.println(t.getEdgeC().getClass().toString());
```

```
77 8980
class org.tinfour.edge.QuadEdgePartner
77 8995
class org.tinfour.edge.QuadEdgePartner
9069 8992
class org.tinfour.edge.QuadEdge

9073 8996
class org.tinfour.edge.QuadEdge
77 8999
class org.tinfour.edge.QuadEdgePartner
77 9001
class org.tinfour.edge.QuadEdgePartner
```

**Comment by gwlucastrig** [comment]
Yikes!

Good catch.  Thanks.  

I am so used to dealing with very large numbers of edges that I've gotten into the habit of using arrays rather than HashMaps.  So I've never exercised the hashCode.  This is one of the many reasons I am grateful that others are looking at my code.

**Comment by gwlucastrig** [comment]
I'm looking at your pull request.

The design for the QuadEdge and QuadEdgePartner classes is a little unusual and I would never recommend it under normal circumstances. When I wrote it, I was trying to accomplish two things. First, I needed to support the concepts in the Quad-Edge data structure. And second, I needed to economize on storage space as much as possible.  

Tinfour edges are bidirectional and being able to treat an edge and its dual symmetrically is very important to the internal logic.  
When I designed the code, the edge needed an ID as a key part of managing the edge pool.  But it only needed one index for the pair.  So to conserve memory, I reserved the index of the "partner" class to serve as a way to store metadata about the edge (such as information related to constraints).   So the partner index is not necessarily zero and it is subject to change as the TIN is constructed. On the other hand, the QuadEdge index is fixed.  You may have wondered why edge index is not declared as "final". Well, it should have been final for the QuadEdge class, but it needed to be changeable for the QuadEdgePartner class.  So I had to compromise. I needed a way to store that metadata. Adding even one additional field to the QuadEdge class would have added 16 bytes to the overall pair. For a Delaunay triangulation with a large number of vertices N, the number of edges approaches 3*N.  So that would have added 48 bytes per vertex to the storage requirements to a TIN.  And since some of the geophysical data sets processed by Tinfour run into the millions of vertices, that's a pretty significant savings.

Anyway, the index for a QuadEdgePartner is always one more than the QuadEdge index.  

One thing I am thinking is that maybe the hashCode could just use:

```
       Integer.hashCode(index)              //   for QuadEdge
       Integer.hashCode(dual.index+1)  // for QuadEdgePartner.
```

It might even make sense to just use the same hashCode for both so that they would tend to be kept close together in memory within the HashMap. But I'm not sure about that one.

I've got a lot of notes on the design of edge classes in the document TinfourAlgorithmsAndDataElements.pdf which is in the doc folder in the main Tinfour distribution.  Here's a screenshot from one of the pages:

![QuadEdgeLinks](https://user-images.githubusercontent.com/19698145/108943040-19494880-7626-11eb-9cb3-603e3d38600b.png)

**Comment by micycle1** [comment]
So an edge and its dual share a parter?

I mirrored the QuadEdge hashcode implementation (77 + index), but if there's no particular reason for that (i.e. it's auto-generated), then it could simply return index as you suggest.

Why do triangles returned by TriangleCollector have 2 QuadEdgePartners and 1 QuadEdge, rather than 3 QuadEdges for example?

> It might even make sense to just use the same hashCode

Bad idea. Different objects should have different hashcodes. The indexes of an edge and its partner seem to be very close anyway.

**Comment by gwlucastrig** [comment]
Thanks about the advice on the bad idea. I use HashMaps all the time for
miscellaneous collections, but they are not my "go to" solution for a
general problem. I guess everyone has their signature move...

The quad edge is essentially a couplet. Two objects permanently linked
together, each representing a different direction of traversal for the two
defining vertices. Then there are 4 links representing transitions to other
edges. These are dynamic and change frequently as the Incremental TIN is
built, but do not change once the Delaunay is finished. I call these links
"forward" and "reverse" though I wish I'd named the accessor methods
something like getForwardLink instead of getForward to make it a bit more
clear what they do. In a valid mesh, all links are fully populated.

For conventional applications, the overhead for constructing Java objects
is negligible. For Tinfour, there are so many objects that it's a problem.
I use an edge pool that lets me re-use edges by changing the links and
repopulating the vertices during insertion. For a large N, the average
number of re-uses is, I believe, 6. So it adds up.

If you make a call to IncrementalTin.printDiagnostics() after you build a
TIN, you see some pretty neat summary of the operations needed to build the
TIN.

Typical lidar data sets include 6 to 12 million samples. Tinfour can
process about 1.6 million points per second on a commodity laptop.

One way to think of the TIN is that it is  kind of collection class
(containing edges and vertices).  I've been playing with different ideas
for making it more collection-like in its available methods. I definitely
need a triangle iterator because the TriangleCollector takes too much code
to use.

Have there been any obvious API elements you'd like to see added (other
than hash codes that actually work)?

Gary
