### ISSUE TITLE
Some pinwheel edges' B vertex are null

### ISSUE THREAD

**Issue by micycle1** [gwlucastrig/Tinfour#86]
Why, for a number of edges in seemingly any tin, are the B vertices of some edges given by pinwheels null? What are these edges? How can this be avoided (particularly when dealing with internal edges, as below)?

```
var edges = new ArrayList<>(triangulation.getEdges());
edges.removeAll(triangulation.getPerimeter());
edges.forEach(e -> {
    e.pinwheel().forEach(e2 -> {
        if (e2.getB() == null) {
            System.out.println(e2.getIndex());
        }
    });
});
```

**Comment by micycle1** [comment]
Figurexd it out: it's  picking up edges whose A vertex lies on the perimeter (perimeter vertices are connected to ghost edges) and it would seem pinwheel **includes** ghost edges😵.

In this case, could it be made clear that the pinwheel operates like this?

Perhaps an additional method signature that takes in a `includeGhostEdges` flag would be appropriate too.

**Comment by gwlucastrig** [comment]
Hi Michael, 
I'm glad that you figured it out.  I was about to write up a note on the topic.   

At the very least, I think I need to add some notes to the Javadoc for the pinwheel() method in IQuadEdge. Do you think I should include something in the wiki, perhaps near [finding the local maximum](https://github.com/gwlucastrig/Tinfour/wiki/Tutorial-Using-Edge-Based-Techniques-Part-1#finding-local-maximum-values-using-the-pinwheel-iterator) ?   Or do you think users would not see it there?  

The choice of using a null reference for the ghost vertex was a mixed bag.  The alternative would have been to have created a special vertex with Double.NaN values for the horizontal coordinates and a method such as isGhost() to allow applications to check to see if it was the ghost vertex. My early experiments showed that the null vertex approach improved the processing throughput when handling a very large set of vertices.  Perhaps because it improved the way Java uses the limited on-chip memory available to an application. But the approach I chose means that code has to check for null references in logic such as the pinwheel iterator.  

Gary

**Comment by micycle1** [comment]
I think it would be worthwhile including a small note in the _Pinwheel Iterator_ section.

**Comment by gwlucastrig** [comment]
Javadoc updated with explanation of the null-reference behavior.
